version: "3"

services:
  app:
    # user: $UID: $GID
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
