# Generated by Django 3.1.3 on 2020-11-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employmentdurationbyagegroup_growthratebyageeducation_pricing_unemploymentbyagegroup_unemploymentbyi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unemploymentbyagegroup',
            old_name='max_duration',
            new_name='median_duration',
        ),
        migrations.RenameField(
            model_name='unemploymentbyindustry',
            old_name='max_duration',
            new_name='median_duration',
        ),
        migrations.RenameField(
            model_name='unemploymentbyoccupation',
            old_name='max_duration',
            new_name='median_duration',
        ),
    ]
