# Generated by Django 3.1.3 on 2020-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201130_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthratebyageeducation',
            name='associates',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growthratebyageeducation',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employmentdurationbyagegroup',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unemploymentbyagegroup',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unemploymentbyindustry',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unemploymentbyoccupation',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
