# Generated by Django 3.1.3 on 2020-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201130_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='unemploymentbyindustry',
            name='indutry_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unemploymentbyoccupation',
            name='occupation_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='age',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='associates',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='attorney',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='bachelors',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='diploma',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='doctorate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='dropout',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='license',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='masters',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='mba',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='professional',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='growthratebyageeducation',
            name='some_college',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='max_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='min_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='payment_cap_factor',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='prepayment_fv',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='prepayment_growth',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='targeted_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='term',
            field=models.IntegerField(unique=True),
        ),
    ]
