# Generated by Django 3.1.3 on 2020-12-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201203_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='max_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='min_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='payment_cap_factor',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='prepayment_fv',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='prepayment_growth',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='targeted_cagr',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
