# Generated by Django 3.1.3 on 2020-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_praisparametercap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praisparametercap',
            name='max_minimum_self_equity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
