# Generated by Django 3.1.3 on 2020-12-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_praisparametercap_isp_age_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='praisparametercap',
            name='minimum_self_equity_perc',
            field=models.DecimalField(decimal_places=3, default=0.05, max_digits=6),
            preserve_default=False,
        ),
    ]
