# Generated by Django 3.1.3 on 2020-12-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_praisparametercap_minimum_self_equity_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='praisparametercap',
            name='isa_maximum_value',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praisparametercap',
            name='max_age_for_quote',
            field=models.IntegerField(default=62),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='praisparametercap',
            name='min_age_for_quote',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
